name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Run the 'make all' target to generate code and Swagger file
    - name: Install dependencies and generate code
      run: make all

    # Upload Swagger files as an artifact
    - name: Upload Swagger JSON
      id: upload-swagger
      uses: actions/upload-artifact@v3
      with:
        name: swagger-json
        path: ./swagger/*.json

    # Output the link to the Swagger artifact in the logs
    - name: Display artifact download link
      run: echo "Swagger file available at: ${{ steps.upload-swagger.outputs.download-url }}"
